### ISSUE TITLE
Sourcemap comment gives error

### ISSUE THREAD

**Issue by stramel** [reworkcss/css#101]
Last line of my file is `/*# sourceMappingURL=main.css.map */`

```
'Error: undefined:1:1: selector missing',
     '    at error (/home/stramel/Projects/app/node_modules/css/lib/parse/index.js:62:15)',
     '    at rule (/home/stramel/Projects/app/node_modules/css/lib/parse/index.js:554:22)',
     '    at rules (/home/stramel/Projects/app/node_modules/css/lib/parse/index.js:117:70)',
     '    at stylesheet (/home/stramel/Projects/app/node_modules/css/lib/parse/index.js:81:21)',
     '    at module.exports (/home/stramel/Projects/app/node_modules/css/lib/parse/index.js:564:20)',
     '    at rework (/home/stramel/Projects/app/node_modules/rework/index.js:27:21)',
     '    at /home/stramel/Projects/app/server/middleware/theme-colors/theme-colors.js:58:28',
     '    at tryToString (fs.js:449:3)',
     '    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)' ] }
```

**Comment by hexagon6** [comment]
@stramel I had a similar error with following comment:

`/*! ....... */`

The parser does not seem to like some characters after `/*` sequence. Fixed by removing the `!`
